[package]
name = "webdir"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]
license = "MIT"
repository = "https://github.com/Tyzzer/webdir"
homepage = "https://github.com/Tyzzer/webdir"
readme = "README.md"
description = "A simple asynchronous static file server"

[[bin]]
name = "webdir"
path = "src/bin/webdir.rs"
doc = false

[features]
sendfile = [ "nix" ]

[dependencies]
xdg = "2.1"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
structopt = "0.0.5"
structopt-derive = "0.0.5"
error-chain = "0.10"

nix = { version = "0.8", optional = true }
libc = "0.2"
bytes = "0.4"
futures = "0.1"
futures-cpupool = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
tokio-proto = "0.1"
hyper = "0.11"

rustls = "0.9"
tokio-rustls = "0.2"

percent-encoding = "1.0"
chrono = "0.3"
humansize = "1.0"
humanesort = "0.1.0-alpha"
base64 = "0.6"
siphasher = "0.2"
smallvec = "0.4"
mime = "0.3"
mime_guess = "2.0.0-alpha.1"
maud = "0.16"
maud_macros = "0.16"

slog = "2.0"
slog-async = "2.0"
slog-term = "2.0"

[dev-dependencies]
tempdir = "0.3"

[profile.release]
lto = true
