[package]
name = "rshttpd"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]

[[bin]]
name = "rshttpd"
path = "src/bin/rshttpd.rs"
doc = false

[dependencies]
clap = "*"
structopt = "*"
structopt-derive = "*"
error-chain = "*"

bytes = "*"
futures = "*"
futures-cpupool = "*"
tokio-io = "*"
tokio-core = "*"
hyper = { git = "https://github.com/hyperium/hyper.git" }

url = "*"
chrono = "*"
humansize = "*"
mime_guess = "*"
maud = "*"
maud_macros = "*"

slog = "2.0.0"
slog-async = "2.0.0"
slog-term = "~2.0.0-4"

[dev-dependencies]
tempdir = "*"
