[package]
name = "webdir"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]
license = "MIT"
repository = "https://github.com/Tyzzer/webdir"
homepage = "https://github.com/Tyzzer/webdir"
readme = "README.md"
description = "A simple asynchronous static file server"
build = "build.rs"
autobins = false

[[bin]]
name = "webdir"
path = "src/bin/webdir.rs"
doc = false

[features]
default = [ "tls" ]

tls = [ "rustls", "tokio-rustls" ]
sendfile = [ "nix", "mio", "bytes" ]
sysalloc = []

[target.'cfg(unix)'.dependencies]
xdg = "2.1"

[dependencies]
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
structopt = "0.2"
structopt-derive = "0.2"
failure = "0.1"

bytes = { version = "0.4", optional = true }
futures = "0.1"
futures-cpupool = "0.1"
mio = { version = "0.6", optional = true }
tokio = "0.1"
tokio-io = "0.1"
hyper = { version = "0.11", default-features = false }

rustls = { version = "0.13", optional = true }
tokio-rustls = { version = "0.7.0", default-features = false, features = [ "tokio" ], optional = true }

percent-encoding = "1.0"
chrono = "0.4"
unbytify = "0.2"
byteorder = "1.0"
humanesort = "0.1.0-alpha"
base64 = "0.9"
siphasher = "0.2"
smallvec = "0.6"
mime = "0.3"
mime_guess = "2.0.0-alpha"
maud = "0.18"
if_chain = "0.1"
rand = "0.5"

slog = { version = "2.0", features = [ "release_max_level_debug" ] }
slog-async = "2.0"
slog-term = "2.0"

nix = { version = "0.11", optional = true }

[dev-dependencies]
tempdir = "0.3"
