[package]
name = "rshttpd"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]

[[bin]]
name = "rshttpd"
path = "src/bin/rshttpd.rs"
doc = false

[dependencies]
xdg = "*"
toml = "*"
serde = "*"
serde_derive = "*"

structopt = "*"
structopt-derive = "*"
error-chain = "*"
smallvec = "*"

bytes = "*"
futures = "*"
futures-cpupool = "*"
tokio-io = "*"
tokio-core = "*"
tokio-proto = "*"
hyper = { git = "https://github.com/hyperium/hyper.git" }

rustls = "*"
tokio-rustls = { version = "*", features = [ "tokio-proto" ] }

url = "*"
chrono = "*"
humansize = "*"
humanesort = "0.1.0-alpha"
data-encoding = "*"
metrohash = "*"
mime_guess = "*"
maud = "*"
maud_macros = "*"

slog = "2.0.0"
slog-async = "2.0.0"
slog-term = "2.0.0"

[dev-dependencies]
tempdir = "*"
