[package]
name = "webdir"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]
license = "MIT"
edition = "2018"
repository = "https://github.com/Tyzzer/webdir"
homepage = "https://github.com/Tyzzer/webdir"
readme = "README.md"
description = "A simple asynchronous static file server"

[[bin]]
name = "webdir"
path = "src/bin/webdir.rs"
doc = false

[features]

[dependencies]
serde = "1.0"
structopt = "0.2"
failure = "0.1"
log = "0.3"

bytes = "*"
tokio = "0.1"
tokio-io = "0.1"
hyper = "0.12"
headers-core = "0.0.1"
headers-ext = "0.0.3"

rustls = { version = "0.14" }
tokio-rustls = { version = "0.8.0", features = ["nightly"] }
ktls = { git = "https://github.com/quininer/ktls" }
tokio-rusktls = { git = "https://github.com/quininer/ktls" }
tokio-linux-aio = "*"

percent-encoding = "1.0"
chrono = "0.4"
unbytify = "0.2"
byteorder = "1.0"
humanesort = "0.1.0-alpha"
base64 = "0.9"
siphasher = "0.2"
smallvec = "0.6"
mime = "0.3"
mime_guess = "2.0.0-alpha"
# maud = "0.18"
if_chain = "0.1"
rand = "0.5"

[replace]
"rustls:0.14.0" = { git = "https://github.com/quininer/rustls", branch = "ktls2" }
